const st={items:[],filter:"all",source:"all",query:"",sort:"priority"};
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const labels={politica:"سیاست",economia:"اقتصاد",sociedad:"جامعه",ciencia:"علم و فناوری",cultura:"فرهنگ",deportes:"ورزش"};
const fd=v=>new Intl.DateTimeFormat("fa-IR",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid"}).format(new Date(v));
async function load(){
 try{const r=await fetch(`data/news.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error("فایل داده پیدا نشد");const d=await r.json();st.items=d.items||[];header(d);sources();render();$("#statusText").textContent=`به‌روزرسانی ${fd(d.generated_at)}`;}
 catch(e){$("#statusText").textContent="خطا در دریافت داده";$("#newsList").innerHTML=`<div class=empty>${esc(e.message)}</div>`;}
}
function header(d){const a=st.items.filter(x=>x.priority>=80), src=new Set(st.items.map(x=>x.source)), p=Math.min(100,Math.round(a.length*10+st.items.length*.7));$("#metricTotal").textContent=st.items.length;$("#metricSources").textContent=src.size;$("#metricAlerts").textContent=a.length;$("#metricUpdated").textContent=fd(d.generated_at).split("،").pop();$("#pulseValue").textContent=p;$("#pulseBar").style.width=p+"%";$("#pulseLabel").textContent=p>=75?"فعالیت خبری بالا":p>=45?"فعالیت خبری متوسط":"وضعیت آرام";$("#alertCount").textContent=a.length;$("#alerts").innerHTML=a.slice(0,5).map(x=>`<div class=alert><b>${esc(x.title_fa||x.title)}</b><span>${esc(x.source)} · ${x.priority}</span></div>`).join("")||"<p>هشدار مهمی ثبت نشده است.</p>";const c={};st.items.forEach(x=>c[x.category]=(c[x.category]||0)+1);const m=Math.max(1,...Object.values(c));$("#topics").innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class=topic><span>${labels[k]||k}</span><div><i style="width:${v/m*100}%"></i></div><b>${v}</b></div>`).join("");}
function sources(){const a=[...new Set(st.items.map(x=>x.source))].sort();$("#sourceFilter").innerHTML='<option value="all">همه منابع</option>'+a.map(x=>`<option>${esc(x)}</option>`).join("");}
function render(){let a=st.items.filter(x=>(st.filter==="all"||x.category===st.filter)&&(st.source==="all"||x.source===st.source)&&`${x.title_fa} ${x.summary_fa} ${x.title} ${x.source}`.toLowerCase().includes(st.query));if(st.sort==="priority")a.sort((x,y)=>y.priority-x.priority||new Date(y.published_at)-new Date(x.published_at));if(st.sort==="newest")a.sort((x,y)=>new Date(y.published_at)-new Date(x.published_at));if(st.sort==="source")a.sort((x,y)=>x.source.localeCompare(y.source));$("#resultCount").textContent=`${a.length} خبر`;$("#newsList").innerHTML=a.length?a.map(x=>`<article class=news><div class=score><div><b>${x.priority}</b><small>اهمیت</small></div></div><div><div class=meta><span class=badge>${labels[x.category]||x.category}</span><span>${esc(x.source)}</span><span>•</span><span>${fd(x.published_at)}</span>${x.ai_translated?'<span>• ترجمه هوشمند</span>':''}</div><h3>${esc(x.title_fa||x.title)}</h3><p>${esc(x.summary_fa||x.summary||"خلاصه‌ای در دسترس نیست.")}</p><span class=original>${esc(x.title)}</span></div><a class=open href="${esc(x.url)}" target=_blank rel=noreferrer>منبع اصلی ↗</a></article>`).join(""):"<div class=empty>خبری با این فیلتر پیدا نشد.</div>";}
$("#filters").onclick=e=>{const b=e.target.closest("button");if(!b)return;document.querySelectorAll("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");st.filter=b.dataset.filter;render()};$("#search").oninput=e=>{st.query=e.target.value.trim().toLowerCase();render()};$("#sourceFilter").onchange=e=>{st.source=e.target.value;render()};$("#sort").onchange=e=>{st.sort=e.target.value;render()};$("#telegramLink").href=(window.APP_CONFIG||{}).telegramChannelUrl||"#";load();